name: Build & Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Recuperation du code source depuis GitHub
        uses: actions/checkout@v3

      # Step 2: Set up JDK 17
      - name: Configurer environnement pour utiliser JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven  # Enable Maven caching for faster builds

      - name: Build Application with Maven
        run: mvn clean package -DskipTests



      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/Gstudent:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name:  Push Docker to dockerhub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/Gstudent:latest