name: Build & Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code source depuis GitHub
        uses: actions/checkout@v3

      # Configuration de Java JDK 17
      - name: Configurer environnement pour utiliser JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Build Application with Maven
        run: mvn clean package -DskipTests

      - name: Définir la date actuelle comme variable d'environnement
        run: echo "TAG_DATE=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      # Utiliser docker/setup-buildx-action avant build-push-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Login à Docker Hub avant de construire l'image
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Construction et push de l'image Docker en une seule étape
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ndigueul/gstudent:latest
            ndigueul/gstudent:${{ github.run_id }}-${{ env.TAG_DATE }}