name: Build & Deploy

on:
  push:
    branches: ["main"]

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Récupération du code source depuis GitHub
        uses: actions/checkout@v3

      # Configuration de Java JDK 17
      - name: Configurer environnement pour utiliser JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven

      - name: Build Application with Maven
        run: mvn clean package -DskipTests

      # Construction de l'image Docker
      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile  # Utiliser 'file' au lieu de 'dockerfile'
          push: false
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gstudent:latest,${{ secrets.DOCKER_HUB_USERNAME }}/gstudent:${{ github.run_id }}-$(date +%y)

      # Connexion à Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Pousser l'image Docker sur Docker Hub
      - name: Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: Dockerfile  # Utiliser 'file' au lieu de 'dockerfile'
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/gstudent:latest,${{ secrets.DOCKER_HUB_USERNAME }}/gstudent:${{ github.run_id }}-$(date +%y)
